---
- name: playbook
  hosts: ec2-3-99-225-217.ca-central-1.compute.amazonaws.com
  become: yes
  roles:
    #- patch
    #- users
    #- nginx
    #- packages
    #- docker-compose
    #- docker
    - sonarqube
    #- mysql
    #- postgres
    #- mongodb

   
